-- MySQL Script generated by MySQL Workbench
-- Mon Jun  8 11:23:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mvcdocker2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mvcdocker2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mvcdocker2` DEFAULT CHARACTER SET utf8 ;
USE `mvcdocker2` ;

-- -----------------------------------------------------
-- Table `mvcdocker2`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_perso` VARCHAR(255) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `date_inserted` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_update` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`mark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`mark` (
  `id_mark` INT NOT NULL AUTO_INCREMENT,
  `note` FLOAT NOT NULL,
  `matiere` VARCHAR(45) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `coefficient` INT NOT NULL,
  `partiel` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_mark`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`planning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`planning` (
  `id_planning` INT NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(45) NOT NULL,
  `course_type` VARCHAR(45) NOT NULL,
  `teacher` VARCHAR(45) NOT NULL,
  `date_start` TIMESTAMP NULL,
  `date_end` TIMESTAMP NULL,
  PRIMARY KEY (`id_planning`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`document` (
  `id_document` INT NOT NULL AUTO_INCREMENT,
  `document_name` VARCHAR(45) NOT NULL,
  `date_inserted` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `matiere` VARCHAR(45) NOT NULL,
  `path` LONGTEXT NOT NULL,
  PRIMARY KEY (`id_document`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`event` (
  `id_event` INT NOT NULL AUTO_INCREMENT,
  `event_name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `place` VARCHAR(150) NOT NULL,
  `date_start` TIMESTAMP NULL,
  `date_end` TIMESTAMP NULL,
  PRIMARY KEY (`id_event`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`role` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(45) NOT NULL,
  `date_inserted` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_update` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`mark_auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`mark_auth` (
  `idMark` INT NOT NULL,
  `idRole` INT NOT NULL,
  `edit` TINYINT NOT NULL DEFAULT 0,
  `read` TINYINT NOT NULL DEFAULT 0,
  `create` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idMark`, `idRole`),
  INDEX `fk_mark_has_role_role1_idx` (`idRole` ASC) VISIBLE,
  INDEX `fk_mark_has_role_mark1_idx` (`idMark` ASC) VISIBLE,
  CONSTRAINT `fk_mark_has_role_mark1`
    FOREIGN KEY (`idMark`)
    REFERENCES `mvcdocker2`.`mark` (`id_mark`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mark_has_role_role1`
    FOREIGN KEY (`idRole`)
    REFERENCES `mvcdocker2`.`role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`document_auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`document_auth` (
  `idRole` INT NOT NULL,
  `idDocument` INT NOT NULL,
  `edit` TINYINT NOT NULL DEFAULT 0,
  `read` TINYINT NOT NULL DEFAULT 0,
  `create` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idRole`, `idDocument`),
  INDEX `fk_role_has_documents_documents1_idx` (`idDocument` ASC) VISIBLE,
  INDEX `fk_role_has_documents_role1_idx` (`idRole` ASC) VISIBLE,
  CONSTRAINT `fk_role_has_documents_role1`
    FOREIGN KEY (`idRole`)
    REFERENCES `mvcdocker2`.`role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_documents_documents1`
    FOREIGN KEY (`idDocument`)
    REFERENCES `mvcdocker2`.`document` (`id_document`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`planning_auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`planning_auth` (
  `idRole` INT NOT NULL,
  `idPlanning` INT NOT NULL,
  `edit` TINYINT NOT NULL DEFAULT 0,
  `read` TINYINT NOT NULL DEFAULT 0,
  `create` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idRole`, `idPlanning`),
  INDEX `fk_role_has_planning_planning1_idx` (`idPlanning` ASC) VISIBLE,
  INDEX `fk_role_has_planning_role1_idx` (`idRole` ASC) VISIBLE,
  CONSTRAINT `fk_role_has_planning_role1`
    FOREIGN KEY (`idRole`)
    REFERENCES `mvcdocker2`.`role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_planning_planning1`
    FOREIGN KEY (`idPlanning`)
    REFERENCES `mvcdocker2`.`planning` (`id_planning`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`global_authorization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`global_authorization` (
  `id_global_authorization` INT NOT NULL AUTO_INCREMENT,
  `mark_edit_auth` TINYINT NOT NULL DEFAULT 0,
  `mark_read_auth` TINYINT NOT NULL DEFAULT 0,
  `mark_create_auth` TINYINT NOT NULL DEFAULT 0,
  `document_edit_auth` TINYINT NOT NULL DEFAULT 0,
  `document_read_auth` TINYINT NOT NULL DEFAULT 0,
  `document_create_auth` TINYINT NOT NULL DEFAULT 0,
  `planning_edit_auth` TINYINT NOT NULL DEFAULT 0,
  `planning_read_auth` TINYINT NOT NULL DEFAULT 0,
  `planning_create_auth` TINYINT NOT NULL DEFAULT 0,
  `user_edit_auth` TINYINT NOT NULL DEFAULT 0,
  `user_read_auth` TINYINT NOT NULL DEFAULT 0,
  `user_create_auth` TINYINT NOT NULL DEFAULT 0,
  `role_edit_auth` TINYINT NOT NULL DEFAULT 0,
  `role_read_auth` TINYINT NOT NULL DEFAULT 0,
  `role_create_auth` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_global_authorization`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`planning_has_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`planning_has_event` (
  `idPlanning` INT NOT NULL,
  `idEvent` INT NOT NULL,
  PRIMARY KEY (`idPlanning`, `idEvent`),
  INDEX `fk_planning_has_events_events1_idx` (`idEvent` ASC) VISIBLE,
  INDEX `fk_planning_has_events_planning1_idx` (`idPlanning` ASC) VISIBLE,
  CONSTRAINT `fk_planning_has_events_planning1`
    FOREIGN KEY (`idPlanning`)
    REFERENCES `mvcdocker2`.`planning` (`id_planning`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planning_has_events_events1`
    FOREIGN KEY (`idEvent`)
    REFERENCES `mvcdocker2`.`event` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`user_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`user_has_role` (
  `idUser` INT NOT NULL,
  `idRole` INT NOT NULL,
  PRIMARY KEY (`idUser`, `idRole`),
  INDEX `fk_user_has_role_role1_idx` (`idRole` ASC) VISIBLE,
  INDEX `fk_user_has_role_user1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_role_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mvcdocker2`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`idRole`)
    REFERENCES `mvcdocker2`.`role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
