-- MySQL Script generated by MySQL Workbench
-- Sun Sep 20 19:25:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mvcdocker2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mvcdocker2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mvcdocker2` DEFAULT CHARACTER SET utf8 ;
USE `mvcdocker2` ;

-- -----------------------------------------------------
-- Table `mvcdocker2`.`nfoz_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`nfoz_users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_perso` VARCHAR(255) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `reset_token` VARCHAR(45) NULL,
  `date_inserted` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_update` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`nfoz_marks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`nfoz_marks` (
  `id_mark` INT NOT NULL AUTO_INCREMENT,
  `note` FLOAT NOT NULL,
  `matiere` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `coefficient` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `date_inserted` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_update` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`id_mark`, `idUser`),
  INDEX `fk_nfoz_marks_nfoz_users1_idx` (`idUser` ASC),
  CONSTRAINT `fk_nfoz_marks_nfoz_users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mvcdocker2`.`nfoz_users` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`nfoz_plannings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`nfoz_plannings` (
  `id_planning` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date_start` DATE NULL,
  `date_end` DATE NULL,
  PRIMARY KEY (`id_planning`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`nfoz_documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`nfoz_documents` (
  `id_document` INT NOT NULL AUTO_INCREMENT,
  `document_name` VARCHAR(45) NOT NULL,
  `date_inserted` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_document`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`nfoz_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`nfoz_events` (
  `id_event` INT NOT NULL AUTO_INCREMENT,
  `event_name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `place` VARCHAR(150) NOT NULL,
  `date_start` TIMESTAMP NULL,
  `date_end` TIMESTAMP NULL,
  PRIMARY KEY (`id_event`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`nfoz_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`nfoz_roles` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(45) NOT NULL,
  `planning` INT NOT NULL,
  `role` INT NOT NULL,
  `mark` INT NOT NULL,
  `document` INT NOT NULL,
  `event` INT NOT NULL,
  `user` INT NOT NULL,
  `page` INT NOT NULL,
  `date_inserted` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_update` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`nfoz_planning_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`nfoz_planning_role` (
  `idRole` INT NOT NULL,
  `idPlanning` INT NOT NULL,
  PRIMARY KEY (`idRole`, `idPlanning`),
  INDEX `fk_role_has_planning_planning1_idx` (`idPlanning` ASC),
  INDEX `fk_role_has_planning_role1_idx` (`idRole` ASC),
  CONSTRAINT `fk_role_has_planning_role1`
    FOREIGN KEY (`idRole`)
    REFERENCES `mvcdocker2`.`nfoz_roles` (`id_role`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_role_has_planning_planning1`
    FOREIGN KEY (`idPlanning`)
    REFERENCES `mvcdocker2`.`nfoz_plannings` (`id_planning`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`nfoz_user_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`nfoz_user_has_role` (
  `idUser` INT NOT NULL,
  `idRole` INT NOT NULL,
  PRIMARY KEY (`idUser`, `idRole`),
  INDEX `fk_user_has_role_role1_idx` (`idRole` ASC),
  INDEX `fk_user_has_role_user1_idx` (`idUser` ASC),
  CONSTRAINT `fk_user_has_role_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mvcdocker2`.`nfoz_users` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`idRole`)
    REFERENCES `mvcdocker2`.`nfoz_roles` (`id_role`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`nfoz_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`nfoz_menu` (
  `id_menu` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `position` INT NOT NULL,
  `date_inserted` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_update` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_menu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`nfoz_pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`nfoz_pages` (
  `id_page` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `date_inserted` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_update` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `idMenu` INT NOT NULL,
  PRIMARY KEY (`id_page`),
  INDEX `fk_nfoz_pages_nfoz_menu1_idx` (`idMenu` ASC),
  CONSTRAINT `fk_nfoz_pages_nfoz_menu1`
    FOREIGN KEY (`idMenu`)
    REFERENCES `mvcdocker2`.`nfoz_menu` (`id_menu`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvcdocker2`.`nfoz_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvcdocker2`.`nfoz_courses` (
  `id_course` INT NOT NULL AUTO_INCREMENT,
  `matiere` VARCHAR(45) NOT NULL,
  `teacher` VARCHAR(45) NOT NULL,
  `date_start` TIMESTAMP NULL,
  `date_end` TIMESTAMP NULL,
  `idPlanning` INT NOT NULL,
  PRIMARY KEY (`id_course`),
  INDEX `fk_courses_nfoz_plannings1_idx` (`idPlanning` ASC),
  CONSTRAINT `fk_courses_nfoz_plannings1`
    FOREIGN KEY (`idPlanning`)
    REFERENCES `mvcdocker2`.`nfoz_plannings` (`id_planning`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
